---
name: build

"on":
  pull_request:
  push:
    branches:
      - master

jobs:
  mac:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: npm install
      - run: npm run build-mac
  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: npm install
      - run: npm run build-win
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: npm install
      - run: npm run build-linux
